# Numpy Functions

In [1]:
import numpy as np

In [2]:
arr = np.ones(2)
arr

array([1., 1.])

In [3]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [4]:
np.zeros(2)

array([0., 0.])

In [5]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [6]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [7]:
arr = np.array([1.432, 3.087, 4.56])
np.round(arr)

array([1., 3., 5.])

In [8]:
np.round(arr, 2)

array([1.43, 3.09, 4.56])

In [9]:
#first 2 arguments is a range, last argument is the number of intersections in the range
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])