# Numpy Arrays

In [1]:
import numpy as np

In [2]:
ar = np.array([1,4,6,3,7])
ar

array([1, 4, 6, 3, 7])

In [3]:
ar1 = np.array((2,3,4,5))
ar1

array([2, 3, 4, 5])

In [4]:
# creating 2-d array

arr = np.array([[1,2,4], [5,6,7]])
arr

array([[1, 2, 4],
       [5, 6, 7]])

In [5]:
# creating 3-d array

arr = np.array([[[1,2,3], [5,6,7], [1,2,3], [5,6,7]]])
arr

array([[[1, 2, 3],
        [5, 6, 7],
        [1, 2, 3],
        [5, 6, 7]]])

In [6]:
ar = np.array([1,4,6,3,7])
ar[2]

6

In [7]:
arr = np.array([[1,2,4], [5,6,8]])
arr[0,1]

2